name: 'Docker::Build'
description: 'Build and push Docker image for Github Docker Registry'
inputs:
  repo:
    description: 'The name of the repo'
    required: true
  name:
    description: 'The name of the image'
    required: true
  username:
    description: 'The login username for the registry'
    required: true
  password:
    description: 'The login password for the registry'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
