name: 'Docker::Build'
description: 'Build and push Docker image for Github Docker Registry'
inputs:
  name:
    description: 'The name of the image'
    required: true
outputs:
  tag:
    description: 'Is the tag, which was pushed'
  digest:
    description: 'Is the digest of the image, which was pushed'
runs:
  using: 'docker'
  image: 'Dockerfile'
